version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: '16'
    volumes:
      - ..:/workspace:cached
      - commons-ts-node_modules:/workspace/node_modules
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Uncomment the next line to use a non-root user for all processes.
    user: node

volumes:
  commons-ts-node_modules:
