name: coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: 'pnpm'
      - run: pnpm install

      - uses: paambaati/codeclimate-action@v5
        continue-on-error: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          coverageCommand: pnpm run test:coverage
          coverageLocations: packages/**/coverage/cobertura-coverage.xml:cobertura
